version: '3'

services:
  client:
    container_name: client
    build:
      context: ./client
    ports:
    - "80:80"
    # - "443:443"
    # volumes:
    # - ./certbot/www:/var/www/certbot/:ro
    # - ./certbot/conf/:/etc/nginx/ssl/:ro
  # certbot:
  #   image: certbot/certbot:latest
  #   volumes:
  #     - ./certbot/www/:/var/www/certbot/:rw
  #     - ./certbot/conf/:/etc/letsencrypt/:rw
  api:
    container_name: api
    user: node
    build:
      context: ./server
    volumes:
    - ../../:/mnt
    environment:
    - EXH_DEMO=true
    - EXH_VERBOSE=true
    - EXH_SITE_SERVER_HOST=0.0.0.0
    - EXH_SITE_SERVER_PORT=80
    ports:
    - "81:80"
