version: '3'

services:
  client:
    container_name: client
    build:
      context: ./client
    ports:
    - ${config.demo.httpPort}:80
    # START config.demo.enableHttps
    - "${config.demo.httpsPort}:443"
    volumes:
    - ${config.demo.certDir}/www:/var/www/certbot/:ro
    - ${config.demo.certDir}/conf/:/etc/nginx/ssl/:ro
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ${config.demo.certDir}/www/:/var/www/certbot/:rw
      - ${config.demo.certDir}/conf/:/etc/letsencrypt/:rw
  # END config.demo.enableHttps
  api:
    container_name: api
    user: node
    build:
      context: ./server
    volumes:
    - ../../:/mnt
    environment:
    - EXH_DEMO=true
    - EXH_VERBOSE=true
    - EXH_SITE_SERVER_HOST=0.0.0.0
    - EXH_SITE_SERVER_PORT=80
    ports:
    - "4001:80"
